version: "3.8"

services:
  face-detection:
    build: .
    ports:
      - "5005:5005"
    volumes:
      - ./face_references.pkl:/app/face_references.pkl # Persistance des données
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
